# Imports of the libary

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Load the dataset
data = pd.read_csv('uncleaned bike sales data.csv')

### Check the header of the data

In [2]:
data.head()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,12/1/2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,12/1/2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,12/2/2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,12/2/2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,12/3/2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00"

### Check the size of the data

In [3]:
# check row and columns
data.shape

(89, 19)

As we can see there is 19 column and 89 rows

### Check the data type of the data

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_Order #        89 non-null     int64
 1   Date                 89 non-null     str
 2   Day                  88 non-null     float64
 3   Month                89 non-null     str
 4   Year                 89 non-null     int64
 5   Customer_Age         89 non-null     int64
 6   Age_Group            88 non-null     str
 7   Customer_Gender      89 non-null     str
 8   Country              89 non-null     str
 9   State                89 non-null     str
 10  Product_Category     89 non-null     str
 11  Sub_Category         89 non-null     str
 12  Product_Description  88 non-null     str
 13  Order_Quantity       88 non-null     float64
 14   Unit_Cost           89 non-null     str
 15   Unit_Price          89 non-null     str
 16   Profit              89 non-null     str
 17   Cost                89 non-null     str
 18  Revenue              89 non-null     str
dtypes: float64(2), int64(3), str(14)
memory usage: 13.3 KB

as we can see month is str we have to convert to int

Unit cost, unit price, profit, cost, revenue are also a string we have to convert to float

# Check for missing values is columns

In [5]:
# Check for missing values
print(data.isnull().sum())

Sales_Order #          0
Date                   0
Day                    1
Month                  0
Year                   0
Customer_Age           0
Age_Group              1
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    1
Order_Quantity         1
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

We can see that age group have one missing value

Product description have one missing value

Order quantity also have one missing value

### Check for duplicated data

In [6]:
# Check for duplicates
print(data.duplicated().sum())

0

All data are unique

### Now we check the date are consistent with the given date

In [7]:
# check consistency of data date in year, month and day
data['Date'] = pd.to_datetime(data['Date'])


data['new_Year'] = data['Date'].dt.year
data['new_Month'] = data['Date'].dt.month
data['new_Day'] = data['Date'].dt.day

we create new columns like new_year, new_month, new_day.

### Check the date data min max value

In [8]:
data.describe()

,Sales_Order #,Date,Day,Year,Customer_Age,Order_Quantity,new_Year,new_Month,new_Day
count,89.000000,89,88.000000,89.0,89.000000,88.000000,89.0,89.0,89.000000
mean,261738.067416,2021-12-13 10:31:00.674157,13.534091,2021.0,34.202247,2.125000,2021.0,12.0,13.438202
min,261695.000000,2021-12-01 00:00:00,1.000000,2021.0,17.000000,1.000000,2021.0,12.0,1.000000
25%,261716.000000,2021-12-08 00:00:00,8.750000,2021.0,30.000000,1.000000,2021.0,12.0,8.000000
50%,261738.000000,2021-12-13 00:00:00,13.500000,2021.0,35.000000,2.000000,2021.0,12.0,13.000000
75%,261760.000000,2021-12-19 00:00:00,19.000000,2021.0,38.000000,3.000000,2021.0,12.0,19.000000
max,261782.000000,2021-12-24 00:00:00,24.000000,2021.0,63.000000,4.000000,2021.0,12.0,24.000000
std,25.729713,NaN,6.391353,0.0,8.090651,1.239322,0.0,0.0,6.418997

### Check that given column data row is missing day

In [9]:
# check that row of day is missing
data[data['Day'].isnull()]

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,...,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,new_Year,new_Month,new_Day
10,261704,2021-12-05,NaN,December,2021,42,Adults (35-64),M,Germany,Nordrhein-Westfalen,...,"Mountain-200 Black, 38",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00",2021,12,5

Replace the value with the new column

In [10]:


# replace missing day with 5th of December
data.loc[data['Day'].isnull(), 'Day'] = 5

In [11]:
data["Month"].unique()

<StringArray>
['December', 'Decmber']
Length: 2, dtype: str

In [12]:
data["Month"] = data["Month"].str.replace("Decmber", "December")

data["Month"] = data["Month"].str.replace("December", "12")


data["Month"].astype(int).unique()

array([12])

In [13]:
# convert day data type from float to int
data = data.dropna(subset=['Day'])
data['Day'] = data['Day'].astype(int)

In [14]:
# check consistency of data date in year, month and day with new columns
true_count = (data['Year'] == data['new_Year']).sum()
false_count = (data['Year'] != data['new_Year']).sum()

print("Year consistency check:")
print("True count:", true_count)
print("False count:", false_count)

true_count = (data['Month'] == data['new_Month']).sum()
false_count = (data['Month'] != data['new_Month']).sum()

print("Month consistency check:")
print("True count:", true_count)
print("False count:", false_count)

true_count = (data['Day'] == data['new_Day']).sum()
false_count = (data['Day'] != data['new_Day']).sum()

print("Day consistency check:")
print("True count:", true_count)
print("False count:", false_count)

Year consistency check:
True count: 89
False count: 0
Month consistency check:
True count: 0
False count: 89
Day consistency check:
True count: 89
False count: 0

### Note that month check are all invalid value

In [15]:
# drop day column
data = data.drop('Day', axis=1)
data = data.drop('Month', axis=1)
data = data.drop('Year', axis=1)

In [16]:
# Age_Group check uniqueness
data['Age_Group'].value_counts()

Age_Group
Adults (35-64)          47
Young Adults (25-34)    31
Youth (<25)             10
Name: count, dtype: int64

In [17]:
data[data['Age_Group'].isnull()]

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,new_Year,new_Month,new_Day
15,261709,2021-12-06,36,NaN,M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1.0,"$1,252.00","$2,295.00","$1,043.00","$1,252.00","$2,295.00",2021,12,6

In [18]:
data.loc[data['Age_Group'].isnull(), 'Age_Group'] = "Adults (35-64)"

In [19]:
# Check consistency of age with age group
def get_age_group(age):
    if age < 25:
        return "Youth (<25)"
    elif age < 35:
        return "Young Adults (25-34)"
    elif age < 65:
        return "Adults (35-64)"
    else:
        return "Elderly (65+)"

invalid_rows = data[
    data["Age_Group"] != data["Customer_Age"].apply(get_age_group)
]

print("Invalid records:", invalid_rows.shape[0])

Invalid records: 0

In [20]:
data["Customer_Age"].apply(get_age_group)

0           Adults (35-64)
1           Adults (35-64)
2           Adults (35-64)
3     Young Adults (25-34)
4           Adults (35-64)
              ...
84          Adults (35-64)
85    Young Adults (25-34)
86    Young Adults (25-34)
87          Adults (35-64)
88          Adults (35-64)
Name: Customer_Age, Length: 89, dtype: str

# all value are consistent with the given age and age_group is consistent

In [21]:
data.head()

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,new_Year,new_Month,new_Day
0,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00",2021,12,1
1,261695,2021-12-01,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00",2021,12,1
2,261697,2021-12-02,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,$420.00,$769.00,$698.00,$840.00,"$1,538.00",2021,12,2
3,261698,2021-12-02,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,$420.00,$769.00,$349.00,$420.00,$769.00,2021,12,2
4,261699,2021-12-03,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,$0.00,"$2,295.00","$2,086.00",$0.00,"$4,590.00",2021,12,3

# check Country have inconsistent value

In [22]:
data["Country"].unique()

<StringArray>
[ 'United States', 'United Kingdom', ' United States',      'Australia',
 'United  States', 'United States ',        'Germany',         'Canada',
         'France']
Length: 9, dtype: str

In [23]:
# This check any country have any space infont and back and replace any more spaces inbetween to single space
data["Country"] = data["Country"].str.strip().str.replace(r"\s+", " ", regex=True)

In [24]:
data["State"].unique()

<StringArray>
[         'California',             'England',     'New South Wales',
          'Washington', 'Nordrhein-Westfalen',          'Queensland',
    'British Columbia',              'Oregon',            'Victoria',
             'Hamburg',       'Seine (Paris)',      'Seine et Marne',
   'Seine Saint Denis',                'Nord',     'South Australia',
              'Hessen',               'Somme']
Length: 17, dtype: str

In [25]:
country_states = {}
# Get unique states for each country
for country in data["Country"].unique():
    country_states[country] = data[data["Country"] == country]["State"].unique()

print(country_states)

{'United States': <StringArray>
['California', 'Washington', 'Oregon']
Length: 3, dtype: str, 'United Kingdom': <StringArray>
['England']
Length: 1, dtype: str, 'Australia': <StringArray>
['New South Wales', 'Queensland', 'Victoria', 'South Australia']
Length: 4, dtype: str, 'Germany': <StringArray>
['Nordrhein-Westfalen', 'Hamburg', 'Hessen']
Length: 3, dtype: str, 'Canada': <StringArray>
['British Columbia']
Length: 1, dtype: str, 'France': <StringArray>
['Seine (Paris)', 'Seine et Marne', 'Seine Saint Denis', 'Nord', 'Somme']
Length: 5, dtype: str}

In [26]:
# map country and state
valid_mapping = data.groupby("Country")["State"].unique().to_dict()
# Reverse mapping (state → countries)
state_country_map = data.groupby("State")["Country"].unique()
# States that appear in more than one country:
invalid_states = state_country_map[state_country_map.apply(len) > 1]
print(invalid_states)

Series([], Name: Country, dtype: object)

In [27]:
# Find exact wrong rows
invalid_rows = data[data["State"].isin(invalid_states.index)]
print(invalid_rows)

Empty DataFrame
Columns: [Sales_Order #, Date, Customer_Age, Age_Group, Customer_Gender, Country, State, Product_Category, Sub_Category, Product_Description, Order_Quantity,  Unit_Cost ,  Unit_Price ,  Profit ,  Cost , Revenue, new_Year, new_Month, new_Day]
Index: []

# Note that Unit_cost, unit_price, profit, cost revenue is string 
it have $ and thousand seperator. to solve this we replace the value using regex

In [28]:
data["Unit_Cost_new"] = data[" Unit_Cost "].str.replace("$", "", regex=False)\
                         .str.replace(",", "", regex=False)\
                         .astype(float)

In [29]:
data["Unit_Price_new"] = data[" Unit_Price "].str.replace("$", "", regex=False)\
                         .str.replace(",", "", regex=False)\
                         .astype(float)

In [30]:
data["Profit_new"] = data[" Profit "].str.replace("$", "", regex=False)\
                         .str.replace(",", "", regex=False)\
                         .astype(float)

In [31]:
data["Cost_new"] = data[" Cost "].str.replace("$", "", regex=False)\
                         .str.replace(",", "", regex=False)\
                         .astype(float)

In [32]:
data["Revenue_new"] = data["Revenue"].str.replace("$", "", regex=False)\
                         .str.replace(",", "", regex=False)\
                         .astype(float)

In [33]:
data.head()

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,...,Cost,Revenue,new_Year,new_Month,new_Day,Unit_Cost_new,Unit_Price_new,Profit_new,Cost_new,Revenue_new
0,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",...,"$5,008.00","$9,180.00",2021,12,1,1252.0,2295.0,4172.0,5008.0,9180.0
1,261695,2021-12-01,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",...,"$1,266.00","$2,320.00",2021,12,1,1266.0,2320.0,1054.0,1266.0,2320.0
2,261697,2021-12-02,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",...,$840.00,"$1,538.00",2021,12,2,420.0,769.0,698.0,840.0,1538.0
3,261698,2021-12-02,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",...,$420.00,$769.00,2021,12,2,420.0,769.0,349.0,420.0,769.0
4,261699,2021-12-03,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",...,$0.00,"$4,590.00",2021,12,3,0.0,2295.0,2086.0,0.0,4590.0

In [34]:
# drop the string values
data.drop([' Unit_Cost ', ' Unit_Price ', ' Profit ', ' Cost ', 'Revenue'], axis=1, inplace=True)
data.head()

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,new_Year,new_Month,new_Day,Unit_Cost_new,Unit_Price_new,Profit_new,Cost_new,Revenue_new
0,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,2021,12,1,1252.0,2295.0,4172.0,5008.0,9180.0
1,261695,2021-12-01,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,2021,12,1,1266.0,2320.0,1054.0,1266.0,2320.0
2,261697,2021-12-02,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,2021,12,2,420.0,769.0,698.0,840.0,1538.0
3,261698,2021-12-02,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,2021,12,2,420.0,769.0,349.0,420.0,769.0
4,261699,2021-12-03,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,2021,12,3,0.0,2295.0,2086.0,0.0,4590.0

In [35]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sales_Order #        89 non-null     int64
 1   Date                 89 non-null     datetime64[us]
 2   Customer_Age         89 non-null     int64
 3   Age_Group            89 non-null     str
 4   Customer_Gender      89 non-null     str
 5   Country              89 non-null     str
 6   State                89 non-null     str
 7   Product_Category     89 non-null     str
 8   Sub_Category         89 non-null     str
 9   Product_Description  88 non-null     str
 10  Order_Quantity       88 non-null     float64
 11  new_Year             89 non-null     int32
 12  new_Month            89 non-null     int32
 13  new_Day              89 non-null     int32
 14  Unit_Cost_new        89 non-null     float64
 15  Unit_Price_new       89 non-null     float64
 16  Profit_new           89 non-null     float64
 17  Cost_new             89 non-null     float64
 18  Revenue_new          89 non-null     float64
dtypes: datetime64[us](1), float64(6), int32(3), int64(2), str(7)
memory usage: 12.3 KB

In [36]:
data.describe()

,Sales_Order #,Date,Customer_Age,Order_Quantity,new_Year,new_Month,new_Day,Unit_Cost_new,Unit_Price_new,Profit_new,Cost_new,Revenue_new
count,89.000000,89,89.000000,88.000000,89.0,89.0,89.000000,89.000000,89.000000,89.000000,89.000000,89.00000
mean,261738.067416,2021-12-13 10:31:00.674157,34.202247,2.125000,2021.0,12.0,13.438202,1052.247191,1940.943820,1848.887640,2204.235955,4043.94382
min,261695.000000,2021-12-01 00:00:00,17.000000,1.000000,2021.0,12.0,1.000000,0.000000,0.000000,245.000000,0.000000,0.00000
25%,261716.000000,2021-12-08 00:00:00,30.000000,1.000000,2021.0,12.0,8.000000,420.000000,2295.000000,1043.000000,1252.000000,2295.00000
50%,261738.000000,2021-12-13 00:00:00,35.000000,2.000000,2021.0,12.0,13.000000,1252.000000,2295.000000,1054.000000,1266.000000,2320.00000
75%,261760.000000,2021-12-19 00:00:00,38.000000,3.000000,2021.0,12.0,19.000000,1266.000000,2320.000000,2954.000000,3756.000000,6750.00000
max,261782.000000,2021-12-24 00:00:00,63.000000,4.000000,2021.0,12.0,24.000000,1912.000000,3400.000000,5908.000000,7592.000000,13500.00000
std,25.729713,NaN,8.090651,1.239322,0.0,0.0,6.418997,440.499001,789.955743,1394.401162,1730.330926,3139.75858

In [37]:
# check for missing values
print(data.isnull().sum())

Sales_Order #          0
Date                   0
Customer_Age           0
Age_Group              0
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    1
Order_Quantity         1
new_Year               0
new_Month              0
new_Day                0
Unit_Cost_new          0
Unit_Price_new         0
Profit_new             0
Cost_new               0
Revenue_new            0
dtype: int64

In [38]:
# check field order_quantity missing
data[data['Order_Quantity'].isnull()]

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,new_Year,new_Month,new_Day,Unit_Cost_new,Unit_Price_new,Profit_new,Cost_new,Revenue_new
22,261716,2021-12-08,35,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-500 Black, 42",NaN,2021,12,8,295.0,540.0,245.0,0.0,0.0

# explore how value is calculated



|unit cost | unit price | Profit | Cost | Revenue| Quantity |
| ---| --- | ---| --- | --- | --- |
| 1252.0 | 2295.0 | 4172.0 | 5008.0 | 9180.0 | 4.0|


formula for profit
profit = (unit cost - unit price) * quantity

formula for revenue 
unit price * quantity

formula for cost
unit cost * quantity

In [39]:
# replace the missing value quantity with the given formula
# quantity = Profit / (unit price - unit cost) 
data['Order_Quantity_checks'] = data['Profit_new'] / (data['Unit_Price_new'] - data['Unit_Cost_new'])

In [40]:
# check valid Order_Quantity with  Order_Quantity_checks
values =data[data['Order_Quantity'] != data['Order_Quantity_checks']]

In [41]:
values = values[[
    "Order_Quantity",
    "Order_Quantity_checks",
    "Unit_Cost_new",
    "Profit_new",
    "Unit_Price_new",
    "Cost_new",
    "Revenue_new"
]]

In [42]:
values

,Order_Quantity,Order_Quantity_checks,Unit_Cost_new,Profit_new,Unit_Price_new,Cost_new,Revenue_new
4,2.0,0.908932,0.0,2086.0,2295.0,0.0,4590.0
8,4.0,-3.323810,420.0,1396.0,0.0,1680.0,0.0
22,NaN,1.000000,295.0,245.0,540.0,0.0,0.0

### Based on the table above we can see inconsistent data with the given formula
the columns 22 is having missing values of order quantity this cause the cost and revenue are invalid while the profit is available

the columns 4 missing the unit cost which cost and the order quantity checks incorrect. 

the columns 8 is similar to the columns 4 while is missing the unit price.

In [43]:
values.loc[22]

Order_Quantity             NaN
Order_Quantity_checks      1.0
Unit_Cost_new            295.0
Profit_new               245.0
Unit_Price_new           540.0
Cost_new                   0.0
Revenue_new                0.0
Name: 22, dtype: float64

In [44]:
# make change to the value
data.loc[22, ['Order_Quantity', "Cost_new", "Revenue_new"]] = [1.0,data.loc[22, "Unit_Cost_new"] * 1.0, data.loc[22, "Unit_Price_new"] * 1.0]

In [45]:
# make change to the value
values.loc[22, ['Order_Quantity', "Cost_new", "Revenue_new"]] = [1.0,values.loc[22, "Unit_Cost_new"] * 1.0, values.loc[22, "Unit_Price_new"] * 1.0]

In [46]:
values

,Order_Quantity,Order_Quantity_checks,Unit_Cost_new,Profit_new,Unit_Price_new,Cost_new,Revenue_new
4,2.0,0.908932,0.0,2086.0,2295.0,0.0,4590.0
8,4.0,-3.323810,420.0,1396.0,0.0,1680.0,0.0
22,1.0,1.000000,295.0,245.0,540.0,295.0,540.0

the value of unit cost new cause the order_quantity_checks value different than the order quantity causing to come out with different value. To mitigate this issue

In [47]:
values.loc[4,"Profit_new"].astype(float) / values.loc[4,"Order_Quantity"].astype(float) - values.loc[4,"Unit_Price_new"].astype(float)

np.float64(-1252.0)

In [48]:
price = 769.0
cost = 420.0
quantity = 4

(price - cost) *quantity

1396.0

In [49]:
# make change to the value
data.loc[4, ['Unit_Cost_new', "Cost_new"]] = [1252.0, 1252*2.0]
values.loc[4, ['Unit_Cost_new', "Cost_new"]] = [1252.0, 1252*2.0]

In [50]:
values.loc[8,"Profit_new"].astype(float) / values.loc[8,"Order_Quantity"].astype(float) + values.loc[8,"Unit_Cost_new"].astype(float)

np.float64(769.0)

In [51]:
# make change to the value
data.loc[8, ['Unit_Price_new', "Revenue_new"]] = [769.0, 769.0*4.0]
values.loc[8, ['Unit_Price_new', "Revenue_new"]] = [769.0, 769.0*4.0]

In [52]:
data.head()

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,new_Year,new_Month,new_Day,Unit_Cost_new,Unit_Price_new,Profit_new,Cost_new,Revenue_new,Order_Quantity_checks
0,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,2021,12,1,1252.0,2295.0,4172.0,5008.0,9180.0,4.000000
1,261695,2021-12-01,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,2021,12,1,1266.0,2320.0,1054.0,1266.0,2320.0,1.000000
2,261697,2021-12-02,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,2021,12,2,420.0,769.0,698.0,840.0,1538.0,2.000000
3,261698,2021-12-02,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,2021,12,2,420.0,769.0,349.0,420.0,769.0,1.000000
4,261699,2021-12-03,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,2021,12,3,1252.0,2295.0,2086.0,2504.0,4590.0,0.908932

In [53]:
# normalized data
products = data[["Product_Description", "Unit_Cost_new", "Unit_Price_new"]]

In [54]:
# check duplicate values
products.duplicated().sum()

np.int64(70)

In [55]:
# drop duplicates
products = products.drop_duplicates()

# check duplicate values
products.duplicated().sum()

np.int64(0)

In [56]:
products.shape

(19, 3)

In [57]:
products.head()

         Product_Description  Unit_Cost_new  Unit_Price_new
0     Mountain-200 Black, 46         1252.0          2295.0
1    Mountain-200 Silver, 42         1266.0          2320.0
2  Mountain-400-W Silver, 46          420.0           769.0
3  Mountain-400-W Silver, 42          420.0           769.0
5     Mountain-200 Black, 38         1252.0          2295.0

In [58]:
# Check same price and same cost
true_count = (products['Unit_Cost_new'] == products['Unit_Price_new']).sum()
false_count = (products['Unit_Cost_new'] != products['Unit_Price_new']).sum()
print("Unit_Cost_new consistency check:")
print("True count:", true_count)
print("False count:", false_count)

Unit_Cost_new consistency check:
True count: 0
False count: 19

In [59]:
 # add a id column for products
products['product_id'] = products.index
products.head()

         Product_Description  Unit_Cost_new  Unit_Price_new  product_id
0     Mountain-200 Black, 46         1252.0          2295.0           0
1    Mountain-200 Silver, 42         1266.0          2320.0           1
2  Mountain-400-W Silver, 46          420.0           769.0           2
3  Mountain-400-W Silver, 42          420.0           769.0           3
5     Mountain-200 Black, 38         1252.0          2295.0           5

In [60]:
# check missing values in product desrciption
products.isna().sum()

Product_Description    1
Unit_Cost_new          0
Unit_Price_new         0
product_id             0
dtype: int64

In [61]:
data["Product_Category"].unique()

<StringArray>
['Bikes']
Length: 1, dtype: str

In [62]:
data["Sub_Category"].unique()

<StringArray>
['Mountain Bikes']
Length: 1, dtype: str

In [63]:
categories = data[["Product_Category","Sub_Category"]]

In [64]:
# remove extra spaces
categories["Product_Category"] = categories["Product_Category"].str.strip()
categories["Sub_Category"] = categories["Sub_Category"].str.strip()

In [65]:
categories = categories.drop_duplicates()

In [66]:
categories["category_id"] = categories.index

In [67]:
categories.head()

  Product_Category    Sub_Category  category_id
0            Bikes  Mountain Bikes            0

In [68]:
categories.shape

(1, 3)

In [69]:
products.head()

         Product_Description  Unit_Cost_new  Unit_Price_new  product_id
0     Mountain-200 Black, 46         1252.0          2295.0           0
1    Mountain-200 Silver, 42         1266.0          2320.0           1
2  Mountain-400-W Silver, 46          420.0           769.0           2
3  Mountain-400-W Silver, 42          420.0           769.0           3
5     Mountain-200 Black, 38         1252.0          2295.0           5

In [70]:
# product_category table 
# category_id | product_id

products_category = products.copy()

# assign same category_id to all rows
products_category["category_id"] = categories.loc[0, "category_id"]

# keep only needed columns
products_category = products_category[["category_id", "product_id"]]

products_category.head()

   category_id  product_id
0            0           0
1            0           1
2            0           2
3            0           3
5            0           5

In [71]:
# customer table

# customer_id | age_group | customer_gender
customers = data[["Customer_Age", "Age_Group", "Customer_Gender", "Country", "State"]]

In [72]:
customers

,Customer_Age,Age_Group,Customer_Gender,Country,State
0,39,Adults (35-64),F,United States,California
1,44,Adults (35-64),M,United Kingdom,England
2,37,Adults (35-64),M,United States,California
3,31,Young Adults (25-34),F,Australia,New South Wales
4,37,Adults (35-64),F,United States,California
...,...,...,...,...,...
84,41,Adults (35-64),M,Germany,Hessen
85,30,Young Adults (25-34),F,United States,Oregon
86,31,Young Adults (25-34),F,Canada,British Columbia
87,35,Adults (35-64),F,United States,California
88,38,Adults (35-64),M,Australia,Queensland

In [73]:
customers.duplicated().sum()

np.int64(16)

In [74]:
customers = customers.drop_duplicates()

In [75]:
customers.shape

(73, 5)

In [76]:
customers["customer_id"] = customers.index

In [77]:
# sales table

# sales_id | customer_id | product_id | order_quantity | sales_date | revenue | cost | profit 
sales = data[["Sales_Order #", "Customer_Age", "Age_Group", "Customer_Gender" ,"Order_Quantity", "Date", "Revenue_new", "Cost_new", "Profit_new"]]
sales.head()

,Sales_Order #,Customer_Age,Age_Group,Customer_Gender,Order_Quantity,Date,Revenue_new,Cost_new,Profit_new
0,261695,39,Adults (35-64),F,4.0,2021-12-01,9180.0,5008.0,4172.0
1,261695,44,Adults (35-64),M,1.0,2021-12-01,2320.0,1266.0,1054.0
2,261697,37,Adults (35-64),M,2.0,2021-12-02,1538.0,840.0,698.0
3,261698,31,Young Adults (25-34),F,1.0,2021-12-02,769.0,420.0,349.0
4,261699,37,Adults (35-64),F,2.0,2021-12-03,4590.0,2504.0,2086.0

In [78]:
sales = pd.merge(
    data,
    customers,
    on=["Customer_Age", "Age_Group", "Customer_Gender"],
    how="left"
)

In [79]:
sales.head()

,Sales_Order #,Date,Customer_Age,Age_Group,Customer_Gender,Country_x,State_x,Product_Category,Sub_Category,Product_Description,...,new_Day,Unit_Cost_new,Unit_Price_new,Profit_new,Cost_new,Revenue_new,Order_Quantity_checks,Country_y,State_y,customer_id
0,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",...,1,1252.0,2295.0,4172.0,5008.0,9180.0,4.0,United States,California,0
1,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",...,1,1252.0,2295.0,4172.0,5008.0,9180.0,4.0,United States,Oregon,21
2,261695,2021-12-01,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",...,1,1252.0,2295.0,4172.0,5008.0,9180.0,4.0,United States,Washington,71
3,261695,2021-12-01,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",...,1,1266.0,2320.0,1054.0,1266.0,2320.0,1.0,United Kingdom,England,1
4,261697,2021-12-02,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",...,2,420.0,769.0,698.0,840.0,1538.0,2.0,United States,California,2

In [80]:
sales = pd.merge(
    sales,
    products,
    on=["Product_Description", "Unit_Cost_new", "Unit_Price_new"],
    how="left"
)

In [81]:
sales = sales[[
    "Sales_Order #",
    "customer_id",
    "product_id",
    "Order_Quantity",
    "Date",
    "Revenue_new",
    "Cost_new",
    "Profit_new"
]]

In [82]:
sales

,Sales_Order #,customer_id,product_id,Order_Quantity,Date,Revenue_new,Cost_new,Profit_new
0,261695,0,0,4.0,2021-12-01,9180.0,5008.0,4172.0
1,261695,21,0,4.0,2021-12-01,9180.0,5008.0,4172.0
2,261695,71,0,4.0,2021-12-01,9180.0,5008.0,4172.0
3,261695,1,1,1.0,2021-12-01,2320.0,1266.0,1054.0
4,261697,2,2,2.0,2021-12-02,1538.0,840.0,698.0
...,...,...,...,...,...,...,...,...
194,261781,55,22,1.0,2021-12-23,540.0,295.0,245.0
195,261781,65,22,1.0,2021-12-23,540.0,295.0,245.0
196,261782,18,15,4.0,2021-12-24,9180.0,5008.0,4172.0
197,261782,30,15,4.0,2021-12-24,9180.0,5008.0,4172.0
198,261782,88,15,4.0,2021-12-24,9180.0,5008.0,4172.0

In [83]:
products

          Product_Description  Unit_Cost_new  Unit_Price_new  product_id
0      Mountain-200 Black, 46         1252.0          2295.0           0
1     Mountain-200 Silver, 42         1266.0          2320.0           1
2   Mountain-400-W Silver, 46          420.0           769.0           2
3   Mountain-400-W Silver, 42          420.0           769.0           3
5      Mountain-200 Black, 38         1252.0          2295.0           5
11    Mountain-200 Silver, 38         1266.0          2320.0          11
15     Mountain-200 Black, 42         1252.0          2295.0          15
17  Mountain-400-W Silver, 38          420.0           769.0          17
19    Mountain-500 Silver, 42          308.0           565.0          19
21                        NaN         1252.0          2295.0          21
22     Mountain-500 Black, 42          295.0           540.0          22
23     Mountain-100 Black, 38         1898.0          3375.0          23
28     Mountain-500 Black, 40          295.0           540.0          28
29    Mountain-100 Silver, 44         1912.0          3400.0          29
42    Mountain-500 Silver, 40          308.0           565.0          42
51    Mountain-200 Silver, 46         1266.0          2320.0          51
63     Mountain-500 Black, 44          295.0           540.0          63
65     Mountain-100 Black, 48         1898.0          3375.0          65
74     Mountain-500 Black, 52          295.0           540.0          74

In [84]:
categories

  Product_Category    Sub_Category  category_id
0            Bikes  Mountain Bikes            0

In [85]:
customers

,Customer_Age,Age_Group,Customer_Gender,Country,State,customer_id
0,39,Adults (35-64),F,United States,California,0
1,44,Adults (35-64),M,United Kingdom,England,1
2,37,Adults (35-64),M,United States,California,2
3,31,Young Adults (25-34),F,Australia,New South Wales,3
4,37,Adults (35-64),F,United States,California,4
...,...,...,...,...,...,...
83,27,Young Adults (25-34),F,Canada,British Columbia,83
84,41,Adults (35-64),M,Germany,Hessen,84
85,30,Young Adults (25-34),F,United States,Oregon,85
86,31,Young Adults (25-34),F,Canada,British Columbia,86
88,38,Adults (35-64),M,Australia,Queensland,88